### ISSUE TITLE
Error on loading `shlib.so`

### ISSUE THREAD

**Issue by SolitudeSF** [andrewchambers/janetsh#23]
Executing `./janetsh` results in
```
error: could not load native ./shlib.so: ./shlib.so: undefined symbol: janet_nanbox_from_double
  in native
  in require [boot.janet] at (50375:50402)
  in import* [boot.janet] at (50815:50834)
  in _thunk [./janetsh] (tailcall) at (24:37)
```

Janet is `0.5.0`

**Comment by andrewchambers** [comment]
I just pushed a fix making the configure script more strict. It may be possible it wasn't finding the  janet headers.

Can you can try ```make clean &&./configure && make ``` now?

If it complains about missing janet headers you can try:

```./configure --janet-header-cflags="-I /PATH/TO/JANETSRC/janet/src/include" ```

before make.

**Comment by andrewchambers** [comment]
If it still doesn't work after that, I wonder if your janetconfig.h file has some different settings, if you don't midn saying, which OS/arch are you using?

**Comment by SolitudeSF** [comment]
still the same error. it doesnt complain about missing headers. i didnt alter anything in janet installation. im on linux x86_64.

**Comment by andrewchambers** [comment]
Hmm, unsure of the cause and I can't reproduce (even with 0.5.0), but would love to fix this for you. Could you try with janet master?

**Comment by SolitudeSF** [comment]
maybe my installation method is wrong. i installed it with meson. maybe something differs in builds with make/meson?

**Comment by andrewchambers** [comment]
I will try with meson.

**Comment by andrewchambers** [comment]
Ok, I have reproduced.

**Comment by andrewchambers** [comment]
If you build with make, I think the issue will go away, but I will look into the cause and try and get it fixed upstream.

**Comment by andrewchambers** [comment]
@bakpakin this is sort of interesting.

**Comment by michaelforney** [comment]
Looks like the difference is that the Makefile adds `-rdynamic` to LDFLAGS, but meson.build does not.

I think it should work with

```diff
diff --git a/meson.build b/meson.build
index 2d3ff80..dfca891 100644
--- a/meson.build
+++ b/meson.build
@@ -30,6 +30,7 @@ dl_dep = cc.find_library('dl', required : false)
 
 # Some options
 add_project_arguments('-DJANET_BUILD="meson"', language : 'c')
+add_project_link_arguments('-rdynamic', language : 'c')
 
 # Include directories
 incdir = include_directories('src/include')
```

**Comment by michaelforney** [comment]
`-rdynamic` causes `-export-dynamic` to be passed to the linker, which is necessary for `shlib.so` to refer back to symbols defined in `janet` like `janet_nanbox_from_double`.

From the GNU ld manual:
> If you use dlopen to load a dynamic object which needs to refer back to the symbols defined by the program, rather than some other dynamic object, then you will probably need to use this option when linking the program itself.

**Comment by andrewchambers** [comment]
Thank you so much.

**Comment by bakpakin** [comment]
This should be fixed upstream on the latest Janet master with meson as of https://github.com/janet-lang/janet/commit/9f3dde3cc7c98047b339e81ed86b2d903d773610

**Comment by andrewchambers** [comment]
Thank you.
